name: Docker

on: [push, pull_request, workflow_dispatch]

env:
  DOCKER_ORG_NAME: bibletranslationtools
  DOCKER_IMAGE_NAME: scriptureaudiovalidator

jobs:
  #build and publish image
  Build-Image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: docker/setup-qemu-action@v2      
      - uses: docker/setup-buildx-action@v2

      - name: Build image with buildx
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

  Push-Images:
    name: Push images if this is a branch
    runs-on: ubuntu-latest
    needs: [Build-Image]
    if: ${{ contains(fromJson('["push"]'), github.event_name) }}
    steps:
      - uses: actions/checkout@v3
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: docker/setup-qemu-action@v2      
      - uses: docker/setup-buildx-action@v2
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DOCKER_HUB_USER: "op://DevOps/dockerhub-adminwa-token/username"
          DOCKER_HUB_TOKEN: "op://DevOps/dockerhub-adminwa-token/credential"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ env.DOCKER_HUB_TOKEN }}
      - name: Set DOC docker tags
        run: |
          echo "TAG_SHA=$DOCKER_ORG_NAME/$DOCKER_IMAGE_NAME:$GITHUB_SHA" >> $GITHUB_ENV && \
          echo "TAG_BRANCH=$DOCKER_ORG_NAME/$DOCKER_IMAGE_NAME:$CI_REF_NAME_SLUG" >> $GITHUB_ENV && \
          echo "TAG_LATEST=$DOCKER_ORG_NAME/$DOCKER_IMAGE_NAME:latest" >> $GITHUB_ENV
